version: '3.4'

services:
  egobot_mysql:
    image: mysql:8
    container_name: egobot_mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - 3306
      - 33060
    volumes:
      - "egobot_mysql_data:/var/lib/mysql"
      - ./my.cnf:/etc/mysql/conf.d/custom.cnf:ro # Mount custom config file
    deploy:
      resources:
        limits:
          memory: 512M
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - egobot_network

  egobot_node:
    image: quote-add-bot-node:1.0.0
    build: ./bot
    container_name: egobot_node
    restart: always
    environment:
      DB_HOST: egobot_mysql
      DB_USERNAME: $MYSQL_USER
      DB_PASSWORD: $MYSQL_PASSWORD
      DB_DATABASE: $MYSQL_DATABASE
      BOT_TOKEN: $BOT_TOKEN
    depends_on:
      egobot_mysql:
        condition: service_healthy
    networks:
      - egobot_network

volumes:
  egobot_mysql_data:
    name: egobot_mysql_data

networks:
  egobot_network:
    driver: bridge
